config/routes.rb
Rails.application.routes.draw do
  resources :fraiskilometriques
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fraiskilometrique.rb
class Fraiskilometrique < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fraiskilometriques_controller.rb
class FraiskilometriquesController < ApplicationController
  before_action :set_fraiskilometrique, only: [:show, :edit, :update, :destroy]

  # GET /fraiskilometriques
  # GET /fraiskilometriques.json
  def index
    @fraiskilometriques = Fraiskilometrique.all
  end

  # GET /fraiskilometriques/1
  # GET /fraiskilometriques/1.json
  def show
  end

  # GET /fraiskilometriques/new
  def new
    @fraiskilometrique = Fraiskilometrique.new
  end

  # GET /fraiskilometriques/1/edit
  def edit
  end

  # POST /fraiskilometriques
  # POST /fraiskilometriques.json
  def create
    @fraiskilometrique = Fraiskilometrique.new(fraiskilometrique_params)

    respond_to do |format|
      if @fraiskilometrique.save
        format.html { redirect_to @fraiskilometrique, notice: 'Fraiskilometrique was successfully created.' }
        format.json { render :show, status: :created, location: @fraiskilometrique }
      else
        format.html { render :new }
        format.json { render json: @fraiskilometrique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fraiskilometriques/1
  # PATCH/PUT /fraiskilometriques/1.json
  def update
    respond_to do |format|
      if @fraiskilometrique.update(fraiskilometrique_params)
        format.html { redirect_to @fraiskilometrique, notice: 'Fraiskilometrique was successfully updated.' }
        format.json { render :show, status: :ok, location: @fraiskilometrique }
      else
        format.html { render :edit }
        format.json { render json: @fraiskilometrique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fraiskilometriques/1
  # DELETE /fraiskilometriques/1.json
  def destroy
    @fraiskilometrique.destroy
    respond_to do |format|
      format.html { redirect_to fraiskilometriques_url, notice: 'Fraiskilometrique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fraiskilometrique
      @fraiskilometrique = Fraiskilometrique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fraiskilometrique_params
      params.require(:fraiskilometrique).permit(:nom, :date, :chevaux, :km, :total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fraiskilometriques_helper.rb
module FraiskilometriquesHelper
end

app/views/fraiskilometriques/_form.html.erb
<%= form_for(fraiskilometrique) do |f| %>
  <% if fraiskilometrique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fraiskilometrique.errors.count, "error") %> prohibited this fraiskilometrique from being saved:</h2>

      <ul>
      <% fraiskilometrique.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %>
    <%= f.text_field :nom, class:"input", id:"nom"%>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, class:"input", id:"date" %>
  </div>

  <div class="field">
    <%= f.label :chevaux %>
    <%= f.number_field :chevaux, class:"input", id:"chevaux" %>
  </div>

  <div class="field">
    <%= f.label :km %>
    <%= f.number_field :km, class:"input", id:"km" %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total, class:"input", id:"total", disabled: true %>
  </div>

  <div class="actions">
    <%= f.submit "valider", id:"actions" %>
  </div>
<% end %>

app/views/fraiskilometriques/edit.html.erb
<h1>Editing Fraiskilometrique</h1>

<%= render 'form', fraiskilometrique: @fraiskilometrique %>

<%= link_to 'Show', @fraiskilometrique %> |
<%= link_to 'Back', fraiskilometriques_path %>

app/views/fraiskilometriques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fraiskilometriques</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Date</th>
      <th>Chevaux</th>
      <th>Km</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fraiskilometriques.each do |fraiskilometrique| %>
      <tr>
        <td><%= fraiskilometrique.nom %></td>
        <td><%= fraiskilometrique.date %></td>
        <td><%= fraiskilometrique.chevaux %></td>
        <td><%= fraiskilometrique.km %></td>
        <td><%= fraiskilometrique.total %></td>
        <td><%= link_to 'Show', fraiskilometrique %></td>
        <td><%= link_to 'Edit', edit_fraiskilometrique_path(fraiskilometrique) %></td>
        <td><%= link_to 'Destroy', fraiskilometrique, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fraiskilometrique', new_fraiskilometrique_path %>

app/views/fraiskilometriques/new.html.erb
<h1>Fraiskilometrique</h1>

<%= render 'form', fraiskilometrique: @fraiskilometrique %>

<%= link_to 'Back', fraiskilometriques_path %>

app/views/fraiskilometriques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @fraiskilometrique.nom %>
</p>

<p>
  <strong>Date:</strong>
  <%= @fraiskilometrique.date %>
</p>

<p>
  <strong>Chevaux:</strong>
  <%= @fraiskilometrique.chevaux %>
</p>

<p>
  <strong>Km:</strong>
  <%= @fraiskilometrique.km %>
</p>

<p>
  <strong>Total:</strong>
  <%= @fraiskilometrique.total %>
</p>

<%= link_to 'Edit', edit_fraiskilometrique_path(@fraiskilometrique) %> |
<%= link_to 'Back', fraiskilometriques_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TPbenoit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>